import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/navBar";

export const metadata: Metadata = {
  title: "GameTracker NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-zinc-800">
        <NavBar />
        <main className="pt-16">{children}</main>
      </body>
    </html>
  );
}
