import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/navBar";

export const metadata: Metadata = {
  title: "GameTracker NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-[#0b0b14]">
        <NavBar />
        <div className="pointer-events-none fixed inset-0 overflow-hidden">
          <div className="absolute -top-32 left-1/2 -translate-x-1/2 w-[600px] h-[600px] bg-indigo-700/10 rounded-full blur-3xl" />
        </div>
        <main className="pt-16">{children}</main>
      </body>
    </html>
  );
}
